void initLedController();
void toggleWaterLed();
void toggleChargingPin();
void toggleBatteryPin();
void clearVoltageLed();
void showVoltageLeds(int leds);
void blinkLeds();
void toggleBlinkingLeds(bool status);
void checkData();
void showBatteryLevel();